D:\Python_Programs\whisperspeech2\a2wav.py: true
D:\Python_Programs\whisperspeech2\inference.py: true
D:\Python_Programs\whisperspeech2\languages.py: true
D:\Python_Programs\whisperspeech2\modules.py: true
D:\Python_Programs\whisperspeech2\pipeline.py: true
D:\Python_Programs\whisperspeech2\quick_test.py: true
D:\Python_Programs\whisperspeech2\s2a_delar_mup_wds_mlang.py: true
D:\Python_Programs\whisperspeech2\s2a_delar_mup_wds_mlang_cond.py: true
D:\Python_Programs\whisperspeech2\t2s_up_wds_mlang_enclm.py: true
_include_python: true
_include_typescript: false
_include_website: false
_scan_depth: 0
